import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'
import {GlobalStateProvider} from '@/components/providers/GlobalStateProvider'
import {ThemeProvider} from 'next-themes'
import {BackgroundProvider} from '@/components/providers/BackgroundProvider'
import NextTopLoader from 'nextjs-toploader'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
})

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<GlobalStateProvider>
						<BackgroundProvider>
							<NextTopLoader showSpinner={false} color="#fff" />

							{children}
						</BackgroundProvider>
					</GlobalStateProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
